### ISSUE TITLE
CSDP system matrix factorization fails

### ISSUE THREAD

**Issue by hongkai-dai** [coin-or/Csdp#9]
Not sure if this is the right place to ask the question. If there is a better place to post the question, please let me know.

I used CSDP to solve our SDP problems, and it works very well for small sized problems. I tried to call it on a larger problem, and received the error "Fails in system matrix factorization, giving up". I use BLAS/LINPACK shipped with Ubuntu 18.04.

My `X` matrix is large, it has about 1000 blocks, but each block is small, with size 4x4, 8x8 and 16x16. Does that mean we only need to apply Cholesky decomposition on each block (with maximal size 16 x 16)? I would think there is no problem to apply Cholesky decomposition on a 16 x 16 matrix.

If it helps, here is the data for my problem
[prob.zip](https://github.com/coin-or/Csdp/files/3218893/prob.zip)

**Comment by hongkai-dai** [comment]
Never mind, the matrix O is very large, with size 19,000 x 19,000. It is understandable that a Cholesky decomposition on a big dense matrix is not successful.

**Comment by brianborchers** [comment]
Note that the error message you got isn't indicating "out of memory" but rather that the system matrix was so badly conditioned that the Cholesky factorization failed.  This is normally caused by excessive linear dependence in the constraints.  You would have gotten an out of memory error if the system didn't have enough memroy for the matrix (the matrix would have needed about 4 gigabytes which your system apparently had available.)

**Comment by hongkai-dai** [comment]
Thanks Brian, I figured out that the problem was that I used a bad BLAS implementation. I switched to using openblas or intel MKL, and then the problem is gone.
